amazon:
  access:
    key: AKIAUQFCBZ7TWRJ7VWWB
    secret-key: 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
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com
server:
  port: 9001
